[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["iwburns <iburns8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
parse-display = "0.4.0"
